// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjaxsseidyolmulaufot.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqYXhzc2VpZHlvbG11bGF1Zm90Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDkwODYsImV4cCI6MjA2NzUyNTA4Nn0.o8qaExzK1SkA_Q1BARc6MVXL_cj-eQHlrVjHQk2zinM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});